# whitelist
branches:
  only:
  - travis
  - travis-dev

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - git submodule update --init --recursive
  - docker build ./bluesky --tag=bluesky

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - docker-compose build

script:
  - docker-compose up
  - pytest ./tests/
  
after_script:
  - docker-compose down
  # - docker-compose run test
