# whitelist
branches:
  only:
  - travis
  - travis-dev

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - git submodule update --init --recursive
  - docker build ./bluesky --tag=bluesky

install:
  - docker-compose build

script:
  - docker-compose run test
