
# whitelist
branches:
  only:
  - travis
  - travis-dev

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - git submodule update --init --recursive
  - docker build ./bluesky --tag=bluesky

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install pytest-docker-compose

script:
  - pytest -v ./tests/

## To use below instead requires to:
## - define a `test` container in docker-compose.yml
## - add `pytest` to requirements.txt
# install:
  # - docker-compose build

# script:
#   -docker-compose run test
