
version: '3'

services:
  test:
    container_name: test
    build: .
    command: pytest ./tests/
    depends_on:
      - bluesky
      - bluebird
    # networks:
    #   - share
    volumes:
      - .:/usr/src/app
  bluesky:
    # Change this to turinginst/bluesky:1.0 when published
    image: bluesky:latest
    volumes:
      - ./bluesky:/usr/src/app
    expose:
      - 9000
      - 9001
# Uncomment to also publish the BlueSky ports externally
#    ports:
#      - 9000:9000
#      - 9001:9001
  bluebird:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5001
    environment:
      - BS_HOST=bluesky

# networks:
#   share:
#     driver: bridge
